<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script>
    const buyFruit = () => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          reject('meiyou买到苹果')
        }, parseInt((Math.random() * 10) + 5) * 1000)
      })
    }
    async function fn() {
      // const result = await buyFruit(); 
      // console.log(result);
      // console.log(2);
      // 如果有未捕获的异常的话，要进行try catch来捕获异常,这样更严谨
      try {
        const result = await buyFruit();
        console.log(result);
        console.log(2);
      } catch (err) {
        console.error(err);
      }
    }
    fn();
    // result.then(
    //   res => {
    //     console.log(res);
    //     console.log('成功');
    //   },
    //   err => {
    //     console.log('失败');
    //   }
    // )
  </script>
</body>

</html>